// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playlist_continuation_schema.proto

package org.schabi.newpipe.extractor.services.youtube.protos.playlist;

public final class PlaylistProtobufContinuation {
  private PlaylistProtobufContinuation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PlaylistContinuationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youtube.playlists.PlaylistContinuation)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
     * @return Whether the parameters field is set.
     */
    boolean hasParameters();
    /**
     * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
     * @return The parameters.
     */
    org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams getParameters();
  }
  /**
   * Protobuf type {@code youtube.playlists.PlaylistContinuation}
   */
  public  static final class PlaylistContinuation extends
      com.google.protobuf.GeneratedMessageLite<
          PlaylistContinuation, PlaylistContinuation.Builder> implements
      // @@protoc_insertion_point(message_implements:youtube.playlists.PlaylistContinuation)
      PlaylistContinuationOrBuilder {
    private PlaylistContinuation() {
    }
    private int bitField0_;
    public static final int PARAMETERS_FIELD_NUMBER = 80226972;
    private org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parameters_;
    /**
     * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
     */
    @java.lang.Override
    public boolean hasParameters() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
     */
    @java.lang.Override
    public org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams getParameters() {
      return parameters_ == null ? org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams.getDefaultInstance() : parameters_;
    }
    /**
     * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
     */
    private void setParameters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams value) {
      value.getClass();
  parameters_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeParameters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams value) {
      value.getClass();
  if (parameters_ != null &&
          parameters_ != org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams.getDefaultInstance()) {
        parameters_ =
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams.newBuilder(parameters_).mergeFrom(value).buildPartial();
      } else {
        parameters_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
     */
    private void clearParameters() {  parameters_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code youtube.playlists.PlaylistContinuation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation, Builder> implements
        // @@protoc_insertion_point(builder_implements:youtube.playlists.PlaylistContinuation)
        org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationOrBuilder {
      // Construct using org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
       */
      @java.lang.Override
      public boolean hasParameters() {
        return instance.hasParameters();
      }
      /**
       * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
       */
      @java.lang.Override
      public org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams getParameters() {
        return instance.getParameters();
      }
      /**
       * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
       */
      public Builder setParameters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams value) {
        copyOnWrite();
        instance.setParameters(value);
        return this;
        }
      /**
       * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
       */
      public Builder setParameters(
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams.Builder builderForValue) {
        copyOnWrite();
        instance.setParameters(builderForValue.build());
        return this;
      }
      /**
       * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
       */
      public Builder mergeParameters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams value) {
        copyOnWrite();
        instance.mergeParameters(value);
        return this;
      }
      /**
       * <code>.youtube.playlists.ContinuationParams parameters = 80226972;</code>
       */
      public Builder clearParameters() {  copyOnWrite();
        instance.clearParameters();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youtube.playlists.PlaylistContinuation)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "parameters_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0001\uea9c\u2641\uea9c\u2641\u0001\u0000\u0000\u0000\uea9c\u2641" +
                "\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation> parser = PARSER;
          if (parser == null) {
            synchronized (org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:youtube.playlists.PlaylistContinuation)
    private static final org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation DEFAULT_INSTANCE;
    static {
      PlaylistContinuation defaultInstance = new PlaylistContinuation();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PlaylistContinuation.class, defaultInstance);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PlaylistContinuation> PARSER;

    public static com.google.protobuf.Parser<PlaylistContinuation> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ContinuationParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youtube.playlists.ContinuationParams)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The playlist ID as a browse one (it should be "VL" + playlist ID)
     * </pre>
     *
     * <code>string browseId = 2;</code>
     * @return The browseId.
     */
    java.lang.String getBrowseId();
    /**
     * <pre>
     * The playlist ID as a browse one (it should be "VL" + playlist ID)
     * </pre>
     *
     * <code>string browseId = 2;</code>
     * @return The bytes for browseId.
     */
    com.google.protobuf.ByteString
        getBrowseIdBytes();

    /**
     * <pre>
     * A PlaylistContinuationProperties message safe-encoded as a Base64 string
     * </pre>
     *
     * <code>string continuationProperties = 3;</code>
     * @return The continuationProperties.
     */
    java.lang.String getContinuationProperties();
    /**
     * <pre>
     * A PlaylistContinuationProperties message safe-encoded as a Base64 string
     * </pre>
     *
     * <code>string continuationProperties = 3;</code>
     * @return The bytes for continuationProperties.
     */
    com.google.protobuf.ByteString
        getContinuationPropertiesBytes();

    /**
     * <code>string playlistId = 35;</code>
     * @return The playlistId.
     */
    java.lang.String getPlaylistId();
    /**
     * <code>string playlistId = 35;</code>
     * @return The bytes for playlistId.
     */
    com.google.protobuf.ByteString
        getPlaylistIdBytes();
  }
  /**
   * Protobuf type {@code youtube.playlists.ContinuationParams}
   */
  public  static final class ContinuationParams extends
      com.google.protobuf.GeneratedMessageLite<
          ContinuationParams, ContinuationParams.Builder> implements
      // @@protoc_insertion_point(message_implements:youtube.playlists.ContinuationParams)
      ContinuationParamsOrBuilder {
    private ContinuationParams() {
      browseId_ = "";
      continuationProperties_ = "";
      playlistId_ = "";
    }
    public static final int BROWSEID_FIELD_NUMBER = 2;
    private java.lang.String browseId_;
    /**
     * <pre>
     * The playlist ID as a browse one (it should be "VL" + playlist ID)
     * </pre>
     *
     * <code>string browseId = 2;</code>
     * @return The browseId.
     */
    @java.lang.Override
    public java.lang.String getBrowseId() {
      return browseId_;
    }
    /**
     * <pre>
     * The playlist ID as a browse one (it should be "VL" + playlist ID)
     * </pre>
     *
     * <code>string browseId = 2;</code>
     * @return The bytes for browseId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrowseIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(browseId_);
    }
    /**
     * <pre>
     * The playlist ID as a browse one (it should be "VL" + playlist ID)
     * </pre>
     *
     * <code>string browseId = 2;</code>
     * @param value The browseId to set.
     */
    private void setBrowseId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      browseId_ = value;
    }
    /**
     * <pre>
     * The playlist ID as a browse one (it should be "VL" + playlist ID)
     * </pre>
     *
     * <code>string browseId = 2;</code>
     */
    private void clearBrowseId() {

      browseId_ = getDefaultInstance().getBrowseId();
    }
    /**
     * <pre>
     * The playlist ID as a browse one (it should be "VL" + playlist ID)
     * </pre>
     *
     * <code>string browseId = 2;</code>
     * @param value The bytes for browseId to set.
     */
    private void setBrowseIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      browseId_ = value.toStringUtf8();

    }

    public static final int CONTINUATIONPROPERTIES_FIELD_NUMBER = 3;
    private java.lang.String continuationProperties_;
    /**
     * <pre>
     * A PlaylistContinuationProperties message safe-encoded as a Base64 string
     * </pre>
     *
     * <code>string continuationProperties = 3;</code>
     * @return The continuationProperties.
     */
    @java.lang.Override
    public java.lang.String getContinuationProperties() {
      return continuationProperties_;
    }
    /**
     * <pre>
     * A PlaylistContinuationProperties message safe-encoded as a Base64 string
     * </pre>
     *
     * <code>string continuationProperties = 3;</code>
     * @return The bytes for continuationProperties.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContinuationPropertiesBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(continuationProperties_);
    }
    /**
     * <pre>
     * A PlaylistContinuationProperties message safe-encoded as a Base64 string
     * </pre>
     *
     * <code>string continuationProperties = 3;</code>
     * @param value The continuationProperties to set.
     */
    private void setContinuationProperties(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      continuationProperties_ = value;
    }
    /**
     * <pre>
     * A PlaylistContinuationProperties message safe-encoded as a Base64 string
     * </pre>
     *
     * <code>string continuationProperties = 3;</code>
     */
    private void clearContinuationProperties() {

      continuationProperties_ = getDefaultInstance().getContinuationProperties();
    }
    /**
     * <pre>
     * A PlaylistContinuationProperties message safe-encoded as a Base64 string
     * </pre>
     *
     * <code>string continuationProperties = 3;</code>
     * @param value The bytes for continuationProperties to set.
     */
    private void setContinuationPropertiesBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      continuationProperties_ = value.toStringUtf8();

    }

    public static final int PLAYLISTID_FIELD_NUMBER = 35;
    private java.lang.String playlistId_;
    /**
     * <code>string playlistId = 35;</code>
     * @return The playlistId.
     */
    @java.lang.Override
    public java.lang.String getPlaylistId() {
      return playlistId_;
    }
    /**
     * <code>string playlistId = 35;</code>
     * @return The bytes for playlistId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlaylistIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(playlistId_);
    }
    /**
     * <code>string playlistId = 35;</code>
     * @param value The playlistId to set.
     */
    private void setPlaylistId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      playlistId_ = value;
    }
    /**
     * <code>string playlistId = 35;</code>
     */
    private void clearPlaylistId() {

      playlistId_ = getDefaultInstance().getPlaylistId();
    }
    /**
     * <code>string playlistId = 35;</code>
     * @param value The bytes for playlistId to set.
     */
    private void setPlaylistIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      playlistId_ = value.toStringUtf8();

    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code youtube.playlists.ContinuationParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams, Builder> implements
        // @@protoc_insertion_point(builder_implements:youtube.playlists.ContinuationParams)
        org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParamsOrBuilder {
      // Construct using org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The playlist ID as a browse one (it should be "VL" + playlist ID)
       * </pre>
       *
       * <code>string browseId = 2;</code>
       * @return The browseId.
       */
      @java.lang.Override
      public java.lang.String getBrowseId() {
        return instance.getBrowseId();
      }
      /**
       * <pre>
       * The playlist ID as a browse one (it should be "VL" + playlist ID)
       * </pre>
       *
       * <code>string browseId = 2;</code>
       * @return The bytes for browseId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getBrowseIdBytes() {
        return instance.getBrowseIdBytes();
      }
      /**
       * <pre>
       * The playlist ID as a browse one (it should be "VL" + playlist ID)
       * </pre>
       *
       * <code>string browseId = 2;</code>
       * @param value The browseId to set.
       * @return This builder for chaining.
       */
      public Builder setBrowseId(
          java.lang.String value) {
        copyOnWrite();
        instance.setBrowseId(value);
        return this;
      }
      /**
       * <pre>
       * The playlist ID as a browse one (it should be "VL" + playlist ID)
       * </pre>
       *
       * <code>string browseId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrowseId() {
        copyOnWrite();
        instance.clearBrowseId();
        return this;
      }
      /**
       * <pre>
       * The playlist ID as a browse one (it should be "VL" + playlist ID)
       * </pre>
       *
       * <code>string browseId = 2;</code>
       * @param value The bytes for browseId to set.
       * @return This builder for chaining.
       */
      public Builder setBrowseIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBrowseIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * A PlaylistContinuationProperties message safe-encoded as a Base64 string
       * </pre>
       *
       * <code>string continuationProperties = 3;</code>
       * @return The continuationProperties.
       */
      @java.lang.Override
      public java.lang.String getContinuationProperties() {
        return instance.getContinuationProperties();
      }
      /**
       * <pre>
       * A PlaylistContinuationProperties message safe-encoded as a Base64 string
       * </pre>
       *
       * <code>string continuationProperties = 3;</code>
       * @return The bytes for continuationProperties.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getContinuationPropertiesBytes() {
        return instance.getContinuationPropertiesBytes();
      }
      /**
       * <pre>
       * A PlaylistContinuationProperties message safe-encoded as a Base64 string
       * </pre>
       *
       * <code>string continuationProperties = 3;</code>
       * @param value The continuationProperties to set.
       * @return This builder for chaining.
       */
      public Builder setContinuationProperties(
          java.lang.String value) {
        copyOnWrite();
        instance.setContinuationProperties(value);
        return this;
      }
      /**
       * <pre>
       * A PlaylistContinuationProperties message safe-encoded as a Base64 string
       * </pre>
       *
       * <code>string continuationProperties = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContinuationProperties() {
        copyOnWrite();
        instance.clearContinuationProperties();
        return this;
      }
      /**
       * <pre>
       * A PlaylistContinuationProperties message safe-encoded as a Base64 string
       * </pre>
       *
       * <code>string continuationProperties = 3;</code>
       * @param value The bytes for continuationProperties to set.
       * @return This builder for chaining.
       */
      public Builder setContinuationPropertiesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContinuationPropertiesBytes(value);
        return this;
      }

      /**
       * <code>string playlistId = 35;</code>
       * @return The playlistId.
       */
      @java.lang.Override
      public java.lang.String getPlaylistId() {
        return instance.getPlaylistId();
      }
      /**
       * <code>string playlistId = 35;</code>
       * @return The bytes for playlistId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPlaylistIdBytes() {
        return instance.getPlaylistIdBytes();
      }
      /**
       * <code>string playlistId = 35;</code>
       * @param value The playlistId to set.
       * @return This builder for chaining.
       */
      public Builder setPlaylistId(
          java.lang.String value) {
        copyOnWrite();
        instance.setPlaylistId(value);
        return this;
      }
      /**
       * <code>string playlistId = 35;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlaylistId() {
        copyOnWrite();
        instance.clearPlaylistId();
        return this;
      }
      /**
       * <code>string playlistId = 35;</code>
       * @param value The bytes for playlistId to set.
       * @return This builder for chaining.
       */
      public Builder setPlaylistIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPlaylistIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youtube.playlists.ContinuationParams)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "browseId_",
              "continuationProperties_",
              "playlistId_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0002#\u0003\u0000\u0000\u0000\u0002\u0208\u0003\u0208#" +
                "\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams> parser = PARSER;
          if (parser == null) {
            synchronized (org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:youtube.playlists.ContinuationParams)
    private static final org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams DEFAULT_INSTANCE;
    static {
      ContinuationParams defaultInstance = new ContinuationParams();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ContinuationParams.class, defaultInstance);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.ContinuationParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ContinuationParams> PARSER;

    public static com.google.protobuf.Parser<ContinuationParams> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PlaylistContinuationPropertiesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youtube.playlists.PlaylistContinuationProperties)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Optional field which should be used to avoid difference behavior with
     * continuations returned by YouTube, starts at 0
     * </pre>
     *
     * <code>int32 requestCount = 1;</code>
     * @return The requestCount.
     */
    int getRequestCount();

    /**
     * <pre>
     * The playlist response starts at 0 if this field is omitted
     * An optional string "PT:" with a PlaylistIndexContinuationParameter message
     * safe-encoded in Base64 appended at the end
     * </pre>
     *
     * <code>string playlistIndexParam = 15;</code>
     * @return The playlistIndexParam.
     */
    java.lang.String getPlaylistIndexParam();
    /**
     * <pre>
     * The playlist response starts at 0 if this field is omitted
     * An optional string "PT:" with a PlaylistIndexContinuationParameter message
     * safe-encoded in Base64 appended at the end
     * </pre>
     *
     * <code>string playlistIndexParam = 15;</code>
     * @return The bytes for playlistIndexParam.
     */
    com.google.protobuf.ByteString
        getPlaylistIndexParamBytes();

    /**
     * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
     * @return Whether the contentFilters field is set.
     */
    boolean hasContentFilters();
    /**
     * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
     * @return The contentFilters.
     */
    org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams getContentFilters();
  }
  /**
   * Protobuf type {@code youtube.playlists.PlaylistContinuationProperties}
   */
  public  static final class PlaylistContinuationProperties extends
      com.google.protobuf.GeneratedMessageLite<
          PlaylistContinuationProperties, PlaylistContinuationProperties.Builder> implements
      // @@protoc_insertion_point(message_implements:youtube.playlists.PlaylistContinuationProperties)
      PlaylistContinuationPropertiesOrBuilder {
    private PlaylistContinuationProperties() {
      playlistIndexParam_ = "";
    }
    private int bitField0_;
    public static final int REQUESTCOUNT_FIELD_NUMBER = 1;
    private int requestCount_;
    /**
     * <pre>
     * Optional field which should be used to avoid difference behavior with
     * continuations returned by YouTube, starts at 0
     * </pre>
     *
     * <code>int32 requestCount = 1;</code>
     * @return The requestCount.
     */
    @java.lang.Override
    public int getRequestCount() {
      return requestCount_;
    }
    /**
     * <pre>
     * Optional field which should be used to avoid difference behavior with
     * continuations returned by YouTube, starts at 0
     * </pre>
     *
     * <code>int32 requestCount = 1;</code>
     * @param value The requestCount to set.
     */
    private void setRequestCount(int value) {
      
      requestCount_ = value;
    }
    /**
     * <pre>
     * Optional field which should be used to avoid difference behavior with
     * continuations returned by YouTube, starts at 0
     * </pre>
     *
     * <code>int32 requestCount = 1;</code>
     */
    private void clearRequestCount() {

      requestCount_ = 0;
    }

    public static final int PLAYLISTINDEXPARAM_FIELD_NUMBER = 15;
    private java.lang.String playlistIndexParam_;
    /**
     * <pre>
     * The playlist response starts at 0 if this field is omitted
     * An optional string "PT:" with a PlaylistIndexContinuationParameter message
     * safe-encoded in Base64 appended at the end
     * </pre>
     *
     * <code>string playlistIndexParam = 15;</code>
     * @return The playlistIndexParam.
     */
    @java.lang.Override
    public java.lang.String getPlaylistIndexParam() {
      return playlistIndexParam_;
    }
    /**
     * <pre>
     * The playlist response starts at 0 if this field is omitted
     * An optional string "PT:" with a PlaylistIndexContinuationParameter message
     * safe-encoded in Base64 appended at the end
     * </pre>
     *
     * <code>string playlistIndexParam = 15;</code>
     * @return The bytes for playlistIndexParam.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlaylistIndexParamBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(playlistIndexParam_);
    }
    /**
     * <pre>
     * The playlist response starts at 0 if this field is omitted
     * An optional string "PT:" with a PlaylistIndexContinuationParameter message
     * safe-encoded in Base64 appended at the end
     * </pre>
     *
     * <code>string playlistIndexParam = 15;</code>
     * @param value The playlistIndexParam to set.
     */
    private void setPlaylistIndexParam(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      playlistIndexParam_ = value;
    }
    /**
     * <pre>
     * The playlist response starts at 0 if this field is omitted
     * An optional string "PT:" with a PlaylistIndexContinuationParameter message
     * safe-encoded in Base64 appended at the end
     * </pre>
     *
     * <code>string playlistIndexParam = 15;</code>
     */
    private void clearPlaylistIndexParam() {

      playlistIndexParam_ = getDefaultInstance().getPlaylistIndexParam();
    }
    /**
     * <pre>
     * The playlist response starts at 0 if this field is omitted
     * An optional string "PT:" with a PlaylistIndexContinuationParameter message
     * safe-encoded in Base64 appended at the end
     * </pre>
     *
     * <code>string playlistIndexParam = 15;</code>
     * @param value The bytes for playlistIndexParam to set.
     */
    private void setPlaylistIndexParamBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      playlistIndexParam_ = value.toStringUtf8();

    }

    public static final int CONTENTFILTERS_FIELD_NUMBER = 104;
    private org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams contentFilters_;
    /**
     * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
     */
    @java.lang.Override
    public boolean hasContentFilters() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
     */
    @java.lang.Override
    public org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams getContentFilters() {
      return contentFilters_ == null ? org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams.getDefaultInstance() : contentFilters_;
    }
    /**
     * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
     */
    private void setContentFilters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams value) {
      value.getClass();
  contentFilters_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeContentFilters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams value) {
      value.getClass();
  if (contentFilters_ != null &&
          contentFilters_ != org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams.getDefaultInstance()) {
        contentFilters_ =
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams.newBuilder(contentFilters_).mergeFrom(value).buildPartial();
      } else {
        contentFilters_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
     */
    private void clearContentFilters() {  contentFilters_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code youtube.playlists.PlaylistContinuationProperties}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties, Builder> implements
        // @@protoc_insertion_point(builder_implements:youtube.playlists.PlaylistContinuationProperties)
        org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationPropertiesOrBuilder {
      // Construct using org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Optional field which should be used to avoid difference behavior with
       * continuations returned by YouTube, starts at 0
       * </pre>
       *
       * <code>int32 requestCount = 1;</code>
       * @return The requestCount.
       */
      @java.lang.Override
      public int getRequestCount() {
        return instance.getRequestCount();
      }
      /**
       * <pre>
       * Optional field which should be used to avoid difference behavior with
       * continuations returned by YouTube, starts at 0
       * </pre>
       *
       * <code>int32 requestCount = 1;</code>
       * @param value The requestCount to set.
       * @return This builder for chaining.
       */
      public Builder setRequestCount(int value) {
        copyOnWrite();
        instance.setRequestCount(value);
        return this;
      }
      /**
       * <pre>
       * Optional field which should be used to avoid difference behavior with
       * continuations returned by YouTube, starts at 0
       * </pre>
       *
       * <code>int32 requestCount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestCount() {
        copyOnWrite();
        instance.clearRequestCount();
        return this;
      }

      /**
       * <pre>
       * The playlist response starts at 0 if this field is omitted
       * An optional string "PT:" with a PlaylistIndexContinuationParameter message
       * safe-encoded in Base64 appended at the end
       * </pre>
       *
       * <code>string playlistIndexParam = 15;</code>
       * @return The playlistIndexParam.
       */
      @java.lang.Override
      public java.lang.String getPlaylistIndexParam() {
        return instance.getPlaylistIndexParam();
      }
      /**
       * <pre>
       * The playlist response starts at 0 if this field is omitted
       * An optional string "PT:" with a PlaylistIndexContinuationParameter message
       * safe-encoded in Base64 appended at the end
       * </pre>
       *
       * <code>string playlistIndexParam = 15;</code>
       * @return The bytes for playlistIndexParam.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPlaylistIndexParamBytes() {
        return instance.getPlaylistIndexParamBytes();
      }
      /**
       * <pre>
       * The playlist response starts at 0 if this field is omitted
       * An optional string "PT:" with a PlaylistIndexContinuationParameter message
       * safe-encoded in Base64 appended at the end
       * </pre>
       *
       * <code>string playlistIndexParam = 15;</code>
       * @param value The playlistIndexParam to set.
       * @return This builder for chaining.
       */
      public Builder setPlaylistIndexParam(
          java.lang.String value) {
        copyOnWrite();
        instance.setPlaylistIndexParam(value);
        return this;
      }
      /**
       * <pre>
       * The playlist response starts at 0 if this field is omitted
       * An optional string "PT:" with a PlaylistIndexContinuationParameter message
       * safe-encoded in Base64 appended at the end
       * </pre>
       *
       * <code>string playlistIndexParam = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlaylistIndexParam() {
        copyOnWrite();
        instance.clearPlaylistIndexParam();
        return this;
      }
      /**
       * <pre>
       * The playlist response starts at 0 if this field is omitted
       * An optional string "PT:" with a PlaylistIndexContinuationParameter message
       * safe-encoded in Base64 appended at the end
       * </pre>
       *
       * <code>string playlistIndexParam = 15;</code>
       * @param value The bytes for playlistIndexParam to set.
       * @return This builder for chaining.
       */
      public Builder setPlaylistIndexParamBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPlaylistIndexParamBytes(value);
        return this;
      }

      /**
       * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
       */
      @java.lang.Override
      public boolean hasContentFilters() {
        return instance.hasContentFilters();
      }
      /**
       * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
       */
      @java.lang.Override
      public org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams getContentFilters() {
        return instance.getContentFilters();
      }
      /**
       * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
       */
      public Builder setContentFilters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams value) {
        copyOnWrite();
        instance.setContentFilters(value);
        return this;
        }
      /**
       * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
       */
      public Builder setContentFilters(
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams.Builder builderForValue) {
        copyOnWrite();
        instance.setContentFilters(builderForValue.build());
        return this;
      }
      /**
       * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
       */
      public Builder mergeContentFilters(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams value) {
        copyOnWrite();
        instance.mergeContentFilters(value);
        return this;
      }
      /**
       * <code>.youtube.playlists.PlaylistContentFiltersParams contentFilters = 104;</code>
       */
      public Builder clearContentFilters() {  copyOnWrite();
        instance.clearContentFilters();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youtube.playlists.PlaylistContinuationProperties)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "requestCount_",
              "playlistIndexParam_",
              "contentFilters_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0001h\u0003\u0000\u0000\u0000\u0001\u0004\u000f\u0208h" +
                "\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties> parser = PARSER;
          if (parser == null) {
            synchronized (org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:youtube.playlists.PlaylistContinuationProperties)
    private static final org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties DEFAULT_INSTANCE;
    static {
      PlaylistContinuationProperties defaultInstance = new PlaylistContinuationProperties();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PlaylistContinuationProperties.class, defaultInstance);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContinuationProperties getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PlaylistContinuationProperties> PARSER;

    public static com.google.protobuf.Parser<PlaylistContinuationProperties> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PlaylistIndexContinuationParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youtube.playlists.PlaylistIndexContinuationParam)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The index cannot be 0 and should be a 100 multiplier (YouTube backends
     * return that requests contain an invalid argument otherwise)
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    int getIndex();
  }
  /**
   * Protobuf type {@code youtube.playlists.PlaylistIndexContinuationParam}
   */
  public  static final class PlaylistIndexContinuationParam extends
      com.google.protobuf.GeneratedMessageLite<
          PlaylistIndexContinuationParam, PlaylistIndexContinuationParam.Builder> implements
      // @@protoc_insertion_point(message_implements:youtube.playlists.PlaylistIndexContinuationParam)
      PlaylistIndexContinuationParamOrBuilder {
    private PlaylistIndexContinuationParam() {
    }
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <pre>
     * The index cannot be 0 and should be a 100 multiplier (YouTube backends
     * return that requests contain an invalid argument otherwise)
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     * The index cannot be 0 and should be a 100 multiplier (YouTube backends
     * return that requests contain an invalid argument otherwise)
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @param value The index to set.
     */
    private void setIndex(int value) {
      
      index_ = value;
    }
    /**
     * <pre>
     * The index cannot be 0 and should be a 100 multiplier (YouTube backends
     * return that requests contain an invalid argument otherwise)
     * </pre>
     *
     * <code>int32 index = 1;</code>
     */
    private void clearIndex() {

      index_ = 0;
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code youtube.playlists.PlaylistIndexContinuationParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam, Builder> implements
        // @@protoc_insertion_point(builder_implements:youtube.playlists.PlaylistIndexContinuationParam)
        org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParamOrBuilder {
      // Construct using org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The index cannot be 0 and should be a 100 multiplier (YouTube backends
       * return that requests contain an invalid argument otherwise)
       * </pre>
       *
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return instance.getIndex();
      }
      /**
       * <pre>
       * The index cannot be 0 and should be a 100 multiplier (YouTube backends
       * return that requests contain an invalid argument otherwise)
       * </pre>
       *
       * <code>int32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        copyOnWrite();
        instance.setIndex(value);
        return this;
      }
      /**
       * <pre>
       * The index cannot be 0 and should be a 100 multiplier (YouTube backends
       * return that requests contain an invalid argument otherwise)
       * </pre>
       *
       * <code>int32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        copyOnWrite();
        instance.clearIndex();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youtube.playlists.PlaylistIndexContinuationParam)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "index_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam> parser = PARSER;
          if (parser == null) {
            synchronized (org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:youtube.playlists.PlaylistIndexContinuationParam)
    private static final org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam DEFAULT_INSTANCE;
    static {
      PlaylistIndexContinuationParam defaultInstance = new PlaylistIndexContinuationParam();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PlaylistIndexContinuationParam.class, defaultInstance);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistIndexContinuationParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PlaylistIndexContinuationParam> PARSER;

    public static com.google.protobuf.Parser<PlaylistIndexContinuationParam> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PlaylistContentFiltersParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youtube.playlists.PlaylistContentFiltersParams)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool hideUnavailableVideos = 1;</code>
     * @return The hideUnavailableVideos.
     */
    boolean getHideUnavailableVideos();

    /**
     * <code>bool showOnlyVideos = 2;</code>
     * @return The showOnlyVideos.
     */
    boolean getShowOnlyVideos();

    /**
     * <pre>
     * Parameter works but doesn't return a Shorts UI as of 09/12/23 (American
     * English date format)
     * </pre>
     *
     * <code>bool showOnlyShorts = 3;</code>
     * @return The showOnlyShorts.
     */
    boolean getShowOnlyShorts();
  }
  /**
   * <pre>
   * Content filters parameters for playlists.
   * Parameters hideUnavailableVideos and showOnlyVideos can be used at the same
   * time, but no videos would be returned in this case
   * </pre>
   *
   * Protobuf type {@code youtube.playlists.PlaylistContentFiltersParams}
   */
  public  static final class PlaylistContentFiltersParams extends
      com.google.protobuf.GeneratedMessageLite<
          PlaylistContentFiltersParams, PlaylistContentFiltersParams.Builder> implements
      // @@protoc_insertion_point(message_implements:youtube.playlists.PlaylistContentFiltersParams)
      PlaylistContentFiltersParamsOrBuilder {
    private PlaylistContentFiltersParams() {
    }
    public static final int HIDEUNAVAILABLEVIDEOS_FIELD_NUMBER = 1;
    private boolean hideUnavailableVideos_;
    /**
     * <code>bool hideUnavailableVideos = 1;</code>
     * @return The hideUnavailableVideos.
     */
    @java.lang.Override
    public boolean getHideUnavailableVideos() {
      return hideUnavailableVideos_;
    }
    /**
     * <code>bool hideUnavailableVideos = 1;</code>
     * @param value The hideUnavailableVideos to set.
     */
    private void setHideUnavailableVideos(boolean value) {
      
      hideUnavailableVideos_ = value;
    }
    /**
     * <code>bool hideUnavailableVideos = 1;</code>
     */
    private void clearHideUnavailableVideos() {

      hideUnavailableVideos_ = false;
    }

    public static final int SHOWONLYVIDEOS_FIELD_NUMBER = 2;
    private boolean showOnlyVideos_;
    /**
     * <code>bool showOnlyVideos = 2;</code>
     * @return The showOnlyVideos.
     */
    @java.lang.Override
    public boolean getShowOnlyVideos() {
      return showOnlyVideos_;
    }
    /**
     * <code>bool showOnlyVideos = 2;</code>
     * @param value The showOnlyVideos to set.
     */
    private void setShowOnlyVideos(boolean value) {
      
      showOnlyVideos_ = value;
    }
    /**
     * <code>bool showOnlyVideos = 2;</code>
     */
    private void clearShowOnlyVideos() {

      showOnlyVideos_ = false;
    }

    public static final int SHOWONLYSHORTS_FIELD_NUMBER = 3;
    private boolean showOnlyShorts_;
    /**
     * <pre>
     * Parameter works but doesn't return a Shorts UI as of 09/12/23 (American
     * English date format)
     * </pre>
     *
     * <code>bool showOnlyShorts = 3;</code>
     * @return The showOnlyShorts.
     */
    @java.lang.Override
    public boolean getShowOnlyShorts() {
      return showOnlyShorts_;
    }
    /**
     * <pre>
     * Parameter works but doesn't return a Shorts UI as of 09/12/23 (American
     * English date format)
     * </pre>
     *
     * <code>bool showOnlyShorts = 3;</code>
     * @param value The showOnlyShorts to set.
     */
    private void setShowOnlyShorts(boolean value) {
      
      showOnlyShorts_ = value;
    }
    /**
     * <pre>
     * Parameter works but doesn't return a Shorts UI as of 09/12/23 (American
     * English date format)
     * </pre>
     *
     * <code>bool showOnlyShorts = 3;</code>
     */
    private void clearShowOnlyShorts() {

      showOnlyShorts_ = false;
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Content filters parameters for playlists.
     * Parameters hideUnavailableVideos and showOnlyVideos can be used at the same
     * time, but no videos would be returned in this case
     * </pre>
     *
     * Protobuf type {@code youtube.playlists.PlaylistContentFiltersParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams, Builder> implements
        // @@protoc_insertion_point(builder_implements:youtube.playlists.PlaylistContentFiltersParams)
        org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParamsOrBuilder {
      // Construct using org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool hideUnavailableVideos = 1;</code>
       * @return The hideUnavailableVideos.
       */
      @java.lang.Override
      public boolean getHideUnavailableVideos() {
        return instance.getHideUnavailableVideos();
      }
      /**
       * <code>bool hideUnavailableVideos = 1;</code>
       * @param value The hideUnavailableVideos to set.
       * @return This builder for chaining.
       */
      public Builder setHideUnavailableVideos(boolean value) {
        copyOnWrite();
        instance.setHideUnavailableVideos(value);
        return this;
      }
      /**
       * <code>bool hideUnavailableVideos = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHideUnavailableVideos() {
        copyOnWrite();
        instance.clearHideUnavailableVideos();
        return this;
      }

      /**
       * <code>bool showOnlyVideos = 2;</code>
       * @return The showOnlyVideos.
       */
      @java.lang.Override
      public boolean getShowOnlyVideos() {
        return instance.getShowOnlyVideos();
      }
      /**
       * <code>bool showOnlyVideos = 2;</code>
       * @param value The showOnlyVideos to set.
       * @return This builder for chaining.
       */
      public Builder setShowOnlyVideos(boolean value) {
        copyOnWrite();
        instance.setShowOnlyVideos(value);
        return this;
      }
      /**
       * <code>bool showOnlyVideos = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearShowOnlyVideos() {
        copyOnWrite();
        instance.clearShowOnlyVideos();
        return this;
      }

      /**
       * <pre>
       * Parameter works but doesn't return a Shorts UI as of 09/12/23 (American
       * English date format)
       * </pre>
       *
       * <code>bool showOnlyShorts = 3;</code>
       * @return The showOnlyShorts.
       */
      @java.lang.Override
      public boolean getShowOnlyShorts() {
        return instance.getShowOnlyShorts();
      }
      /**
       * <pre>
       * Parameter works but doesn't return a Shorts UI as of 09/12/23 (American
       * English date format)
       * </pre>
       *
       * <code>bool showOnlyShorts = 3;</code>
       * @param value The showOnlyShorts to set.
       * @return This builder for chaining.
       */
      public Builder setShowOnlyShorts(boolean value) {
        copyOnWrite();
        instance.setShowOnlyShorts(value);
        return this;
      }
      /**
       * <pre>
       * Parameter works but doesn't return a Shorts UI as of 09/12/23 (American
       * English date format)
       * </pre>
       *
       * <code>bool showOnlyShorts = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearShowOnlyShorts() {
        copyOnWrite();
        instance.clearShowOnlyShorts();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youtube.playlists.PlaylistContentFiltersParams)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "hideUnavailableVideos_",
              "showOnlyVideos_",
              "showOnlyShorts_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0007\u0002\u0007" +
                "\u0003\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams> parser = PARSER;
          if (parser == null) {
            synchronized (org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:youtube.playlists.PlaylistContentFiltersParams)
    private static final org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams DEFAULT_INSTANCE;
    static {
      PlaylistContentFiltersParams defaultInstance = new PlaylistContentFiltersParams();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PlaylistContentFiltersParams.class, defaultInstance);
    }

    public static org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation.PlaylistContentFiltersParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PlaylistContentFiltersParams> PARSER;

    public static com.google.protobuf.Parser<PlaylistContentFiltersParams> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
